theme: jekyll-theme-cayman
description: "This portfolio includes various projects that I have completed/worked on in the past! Scroll down to see my projects within the realms of game development, 3D modeling, and music. Additionally, click the button below to see all of my repositories, which also include some software engineering work."
github:
  repository_url: https://github.com/micoo227?tab=repositories
